# Generated by Django 5.0.6 on 2024-06-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите айди чата Телеграмм', max_length=50, null=True, verbose_name='айди чата Телеграмм'),
        ),
    ]
