# Generated by Django 5.0.6 on 2024-06-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_tg_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tg_chat_id',
            new_name='chat_id',
        ),
    ]
